site_name: AVLite Documentation
site_description: Modular Autonomous Vehicle Stack
site_author: AV-Lab

repo_name: AV-Lab/avlite
repo_url: https://github.com/AV-Lab/avlite

theme:
  name: material
  icon:
    logo: material/fire
  favicon: imgs/logo-black-bg.png
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Plugin Development: plugin-development.md

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.details
